add items, add users
KiselevAlecksey/java-shareit pull request #1
Opened 2024-09-21 09:44 UTC by KiselevAlecksey

2024-09-22 10:53 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.error("Create booking {} start", bookingRequest);
Логирование начала выполнения и окончания - это перебор)
Достаточно логировать или начало операции (создается, обновляется, удаляется то-то) или факт выполнения метода (что-то создано, обновлено, удалено)
Плюс т.к. это не ошибка, то error() не подходит, лучше log.info()

2024-09-22 10:56 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingResponse create(@RequestBody NewBookingRequest bookingRequest) {
К полям Dto нужно добавить аннотации валидации, а для параметра метода `@Valid`

2024-09-22 11:14 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/InMemBookingRepository.java
> +    private final ItemRepository itemRepository;
В репозитории лучше оставить банальную логику по созданию, обновлению, получению и удалению сущности одного типа. Зависимость от  ItemRepository и логику связанную с ним лучше вынести в класс сервиса BookingServiceImpl (это его зона ответственности).

2024-09-22 11:15 UTC, VadimZharkov requested changes
Сделано больше, чем требовалось по ТЗ. Посмотри, что можно улучшить.

2024-09-22 17:18 UTC, KiselevAlecksey commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingResponse create(@RequestBody NewBookingRequest bookingRequest) {
Сделал, только не очень понятно, как валидировать и нужно ли валидировать поля description и available, при создании, на что проверять и при обновлении.

2024-09-23 04:11 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingResponse create(@RequestBody NewBookingRequest bookingRequest) {
Нужность валидации определенных полей определяется из логики или если в ТЗ прямо сказано.
Сама валидация с помощью аннотаций работает след. образом: спринг в рантайме по наличию аннотаций @Valid на параметре метода и @NotBlank, @NotNull, @Email и т.д. на полях dto проверяет значения помеченных полей. Если валидация не проходит, то спринг выбрасывает MethodArgumentNotValidException. Ловим его в ErrorHandler

2024-09-23 04:13 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/NewBookingRequest.java
> +    @NotBlank
`@NotBlank` используется только для строк. Для Long лучше `@NotNull`

2024-09-23 04:27 UTC, VadimZharkov requested changes
Можно улучшить

2024-09-23 11:54 UTC, VadimZharkov approved these changes

2024-09-26 22:22 UTC, merged